// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(SISContext))]
    [Migration("20180414115109_Admins")]
    partial class Admins
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.UsersNotSercure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("UsersNotSercure");

                    b.HasData(
                        new { Id = 1, IsAdmin = true, Name = "adam", Password = "test" },
                        new { Id = 2, IsAdmin = false, Name = "rafal", Password = "test2" },
                        new { Id = 3, IsAdmin = false, Name = "ewa", Password = "test3" },
                        new { Id = 4, IsAdmin = false, Name = "asia", Password = "test4" }
                    );
                });

            modelBuilder.Entity("WebApplication1.Models.UsersSecure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(true);

                    b.Property<string>("Salt")
                        .IsRequired()
                        .IsUnicode(true);

                    b.HasKey("Id");

                    b.ToTable("UsersSecure");

                    b.HasData(
                        new { Id = 1, IsAdmin = true, Name = "adam", Password = "My1VzKf/HYSEfmWCSpXaJc7GhKApd8ZP11waj8CuoSw=", Salt = "S3Cr7zOOK6nNqjbnQGUFnA==" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
